spandsp: t30_local.h File Reference
t30_local.h File Reference
Functions
int t30_build_dis_or_dtc (t30_state_t *s)
Function Documentation
t30_build_dis_or_dtc()
int t30_build_dis_or_dtc (t30_state_t * s)
endif‍/
References t30_state_s::local_dis_dtc_frame.
Referenced by t30_set_ecm_capability(), t30_set_minimum_scan_line_time(), t30_set_supported_bilevel_resolutions(), t30_set_supported_colour_resolutions(), t30_set_supported_compressions(), t30_set_supported_modems(), and t30_set_supported_t30_features().