spandsp: t85_encode.c File Reference
t85_encode.c File Reference
#include <inttypes.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "spandsp/stdbool.h"
#include "spandsp/telephony.h"
#include "spandsp/alloc.h"
#include "spandsp/unaligned.h"
#include "spandsp/logging.h"
#include "spandsp/async.h"
#include "spandsp/timezone.h"
#include "spandsp/t4_rx.h"
#include "spandsp/t4_tx.h"
#include "spandsp/t81_t82_arith_coding.h"
#include "spandsp/t85.h"
#include "spandsp/private/logging.h"
#include "spandsp/private/t81_t82_arith_coding.h"
#include "spandsp/private/t85.h"
Enumerations
enum { NEWLEN_NONE = 0, NEWLEN_PENDING = 1, NEWLEN_HANDLED = 2 }
Functions
void t85_encode_set_options (t85_encode_state_t *s, uint32_t l0, int mx, int options)
Set the T.85 options.
int t85_encode_set_image_width (t85_encode_state_t *s, uint32_t image_width)
Set the image width.
int t85_encode_set_image_length (t85_encode_state_t *s, uint32_t image_length)
Alter the length of a T.85 encoded image. The new length cannot be greater than the originally specified length. If the new length is less than the current length it will be silently adjusted to the current length. Therefore, adjust the length to 1 will make the currently encoded length the final length.
void t85_encode_abort (t85_encode_state_t *s)
Stop image encoding prematurely.
void t85_encode_comment (t85_encode_state_t *s, const uint8_t comment[], size_t len)
Insert a comment in the encoded file.
int t85_encode_image_complete (t85_encode_state_t *s)
Check if we are at the end of the current document page.
int t85_encode_get (t85_encode_state_t *s, uint8_t buf[], size_t max_len)
Get the next chunk of the current document page. The document will be padded for the current minimum scan line time.
uint32_t t85_encode_get_image_width (t85_encode_state_t *s)
Get the width of the image.
uint32_t t85_encode_get_image_length (t85_encode_state_t *s)
Get the length of the image.
int t85_encode_get_compressed_image_size (t85_encode_state_t *s)
Get the size of the compressed image, in bits.
int t85_encode_set_row_read_handler (t85_encode_state_t *s, t4_row_read_handler_t handler, void *user_data)
Set the row read handler for a T.85 encode context.
logging_state_t * t85_encode_get_logging_state (t85_encode_state_t *s)
Get the logging context associated with a T.85 encode context.
int t85_encode_restart (t85_encode_state_t *s, uint32_t image_width, uint32_t image_length)
Restart a T.85 encode context.
t85_encode_state_t * t85_encode_init (t85_encode_state_t *s, uint32_t image_width, uint32_t image_length, t4_row_read_handler_t handler, void *user_data)
Prepare to encode an image in T.85 format.
int t85_encode_release (t85_encode_state_t *s)
Release a T.85 encode context.
int t85_encode_free (t85_encode_state_t *s)
Free a T.85 encode context.
Function Documentation
t85_encode_abort()
void t85_encode_abort (t85_encode_state_t * s)
Stop image encoding prematurely.
Parameters
s The T.85 context.
t85_encode_comment()
void t85_encode_comment (t85_encode_state_t * s, const uint8_t comment[], size_t len)
Insert a comment in the encoded file.
Parameters
s The T.85 context.
comment The comment. Note that this is not a C string, and may contain any bytes.
len The length of the comment.
References t85_decode_state_s::comment, and t85_decode_state_s::s.
t85_encode_free()
int t85_encode_free (t85_encode_state_t * s)
Free a T.85 encode context.
Parameters
s The T.85 encode context.
Returns
0 for OK, else -1.
References t85_decode_state_s::s, and t85_encode_release().
t85_encode_get()
int t85_encode_get (t85_encode_state_t * s, uint8_t buf[], size_t max_len)
Get the next chunk of the current document page. The document will be padded for the current minimum scan line time.
Parameters
s The T.85 context.
buf The buffer into which the chunk is to written.
max_len The maximum length of the chunk.
Returns
The actual length of the chunk. If this is less than max_len it indicates that the end of the document has been reached.
t85_encode_get_compressed_image_size()
int t85_encode_get_compressed_image_size (t85_encode_state_t * s)
Get the size of the compressed image, in bits.
Parameters
s The T.85 context.
Returns
The size of the compressed image, in bits.
References t85_decode_state_s::s.
Referenced by t4_tx_get_transfer_statistics().
t85_encode_get_image_length()
uint32_t t85_encode_get_image_length (t85_encode_state_t * s)
Get the length of the image.
Parameters
s The T.85 context.
Returns
The length of the image, in pixels.
References t85_decode_state_s::s.
Referenced by t4_tx_get_transfer_statistics().
t85_encode_get_image_width()
uint32_t t85_encode_get_image_width (t85_encode_state_t * s)
Get the width of the image.
Parameters
s The T.85 context.
Returns
The width of the image, in pixels.
References t85_decode_state_s::s.
Referenced by t4_tx_get_transfer_statistics().
t85_encode_get_logging_state()
logging_state_t* t85_encode_get_logging_state (t85_encode_state_t * s)
Get the logging context associated with a T.85 encode context.
Get the logging context associated with a T.85 encode context.
Parameters
s The T.85 encode context.
Returns
A pointer to the logging context
References t85_decode_state_s::s.
t85_encode_image_complete()
int t85_encode_image_complete (t85_encode_state_t * s)
Check if we are at the end of the current document page.
Parameters
s The T.85 context.
Returns
0 for more data to come. SIG_STATUS_END_OF_DATA for no more data.
References t85_decode_state_s::s, and SIG_STATUS_END_OF_DATA.
Referenced by t4_tx_image_complete().
t85_encode_init()
t85_encode_state_t* t85_encode_init (t85_encode_state_t * s, uint32_t image_width, uint32_t image_length, t4_row_read_handler_t handler, void * user_data)
Prepare to encode an image in T.85 format.
Parameters
s The T.85 context.
image_width The image width, in pixels.
image_length The image length, in pixels.
handler A callback routine to handle encoded image rows.
user_data An opaque pointer passed to handler.
Returns
A pointer to the context, or NULL if there was a problem.
References t85_decode_state_s::s.
t85_encode_release()
int t85_encode_release (t85_encode_state_t * s)
Release a T.85 encode context.
Parameters
s The T.85 encode context.
Returns
0 for OK, else -1.
References t85_decode_state_s::s.
Referenced by t43_encode_free(), t43_encode_release(), and t85_encode_free().
t85_encode_restart()
int t85_encode_restart (t85_encode_state_t * s, uint32_t image_width, uint32_t image_length)
Restart a T.85 encode context.
Parameters
s The T.85 context.
image_width The image width, in pixels.
image_length The image length, in pixels.
Returns
0 for success, otherwise -1.
References t85_decode_state_s::bytes_per_row, t85_decode_state_s::s, and t85_encode_set_image_width().
t85_encode_set_image_length()
int t85_encode_set_image_length (t85_encode_state_t * s, uint32_t image_length)
Alter the length of a T.85 encoded image. The new length cannot be greater than the originally specified length. If the new length is less than the current length it will be silently adjusted to the current length. Therefore, adjust the length to 1 will make the currently encoded length the final length.
Parameters
s The T.85 context.
image_length The new image length, in pixels.
Returns
0 if OK, or -1 if the request was not valid.
References t85_decode_state_s::s, and T85_VLENGTH.
t85_encode_set_image_width()
int t85_encode_set_image_width (t85_encode_state_t * s, uint32_t image_width)
Set the image width.
Parameters
s The T.85 context.
image_width The width of the image.
Returns
0 for success, otherwise -1.
References t85_decode_state_s::bytes_per_row, and t85_decode_state_s::s.
Referenced by t85_encode_restart().
t85_encode_set_options()
void t85_encode_set_options (t85_encode_state_t * s, uint32_t l0, int mx, int options)
Set the T.85 options.
Parameters
s The T.85 context.
l0 ???
mx ???
options ???.
References t85_decode_state_s::l0, t85_decode_state_s::mx, t85_decode_state_s::options, t85_decode_state_s::s, T85_LRLTWO, T85_TPBON, T85_VLENGTH, and t85_decode_state_s::yd.
t85_encode_set_row_read_handler()
int t85_encode_set_row_read_handler (t85_encode_state_t * s, t4_row_read_handler_t handler, void * user_data)
Set the row read handler for a T.85 encode context.
Parameters
s The T.85 context.
handler A pointer to the handler routine.
user_data An opaque pointer passed to the handler routine.
Returns
0 for success, otherwise -1.
References t85_decode_state_s::s.