spandsp: v22bis.h File Reference
v22bis.h File Reference
Macros
#define V22BIS_CONSTELLATION_SCALING_FACTOR 1.0
Typedefs
typedef struct v22bis_state_s v22bis_state_t
Enumerations
enum v22bis_options_t {
V22BIS_GUARD_TONE_NONE = 0, V22BIS_GUARD_TONE_550HZ = 1, V22BIS_GUARD_TONE_1800HZ = 2, V22BIS_BELL212A_COMPATIBILITY_MODE = 0x100,
V22BIS_USE_U00 = 0x200
}
Functions
int v22bis_rx (v22bis_state_t *s, const int16_t amp[], int len)
Process a block of received V.22bis modem audio samples.
int v22bis_rx_fillin (v22bis_state_t *s, int len)
Fake processing of a missing block of received V.22bis modem audio samples.
int v22bis_rx_equalizer_state (v22bis_state_t *s, complexf_t **coeffs)
Get a snapshot of the current equalizer coefficients.
float v22bis_rx_carrier_frequency (v22bis_state_t *s)
float v22bis_rx_symbol_timing_correction (v22bis_state_t *s)
float v22bis_rx_signal_power (v22bis_state_t *s)
void v22bis_rx_set_signal_cutoff (v22bis_state_t *s, float cutoff)
void v22bis_rx_set_qam_report_handler (v22bis_state_t *s, qam_report_handler_t handler, void *user_data)
int v22bis_tx (v22bis_state_t *s, int16_t amp[], int len)
Generate a block of V.22bis modem audio samples.
void v22bis_tx_power (v22bis_state_t *s, float power)
Adjust a V.22bis modem transmit context's output power.
int v22bis_restart (v22bis_state_t *s, int bit_rate)
Reinitialise an existing V.22bis modem context.
int v22bis_request_retrain (v22bis_state_t *s, int bit_rate)
Request a retrain for a V.22bis modem context.
int v22bis_remote_loopback (v22bis_state_t *s, bool enable)
Request a loopback 2 for a V.22bis modem context.
int v22bis_get_current_bit_rate (v22bis_state_t *s)
Report the current operating bit rate of a V.22bis modem context.
v22bis_state_t * v22bis_init (v22bis_state_t *s, int bit_rate, int options, bool calling_party, span_get_bit_func_t get_bit, void *get_bit_user_data, span_put_bit_func_t put_bit, void *put_bit_user_data)
Initialise a V.22bis modem context.
int v22bis_release (v22bis_state_t *s)
Release a V.22bis modem receive context.
int v22bis_free (v22bis_state_t *s)
Free a V.22bis modem receive context.
logging_state_t * v22bis_get_logging_state (v22bis_state_t *s)
Get the logging context associated with a V.22bis modem context.
void v22bis_set_get_bit (v22bis_state_t *s, span_get_bit_func_t get_bit, void *user_data)
Change the get_bit function associated with a V.22bis modem context.
void v22bis_set_put_bit (v22bis_state_t *s, span_put_bit_func_t put_bit, void *user_data)
Change the put_bit function associated with a V.22bis modem context.
void v22bis_set_modem_status_handler (v22bis_state_t *s, span_modem_status_func_t handler, void *user_data)
Change the modem status report function associated with a V.22bis modem receive context.
Typedef Documentation
v22bis_state_t
typedef struct v22bis_state_s v22bis_state_t
V.22bis modem descriptor. This defines the working state for a single instance of a V.22bis modem.
Function Documentation
v22bis_free()
int v22bis_free (v22bis_state_t * s)
Free a V.22bis modem receive context.
Free a V.22bis modem receive context.
Parameters
s The modem context.
Returns
0 for OK
v22bis_get_current_bit_rate()
int v22bis_get_current_bit_rate (v22bis_state_t * s)
Report the current operating bit rate of a V.22bis modem context.
Report the current operating bit rate of a V.22bis modem context.
Parameters
s The modem context.
v22bis_get_logging_state()
logging_state_t* v22bis_get_logging_state (v22bis_state_t * s)
Get the logging context associated with a V.22bis modem context.
Get the logging context associated with a V.22bis modem context.
Parameters
s The modem context.
Returns
A pointer to the logging context
References v22bis_state_s::logging.
v22bis_init()
v22bis_state_t* v22bis_init (v22bis_state_t * s, int bit_rate, int options, bool calling_party, span_get_bit_func_t get_bit, void * get_bit_user_data, span_put_bit_func_t put_bit, void * put_bit_user_data)
Initialise a V.22bis modem context.
Initialise a V.22bis modem context. This must be called before the first use of the context, to initialise its contents.
Parameters
s The modem context.
bit_rate The bit rate of the modem. Valid values are 1200 and 2400.
options Guard tone and other options.
calling_party True if this is the calling modem.
get_bit The callback routine used to get the data to be transmitted.
get_bit_user_data An opaque pointer, passed in calls to the get_bit routine.
put_bit The callback routine used to put the data received.
put_bit_user_data An opaque pointer, passed in calls to the put_bit routine.
Returns
A pointer to the modem context, or NULL if there was a problem.
v22bis_release()
int v22bis_release (v22bis_state_t * s)
Release a V.22bis modem receive context.
Release a V.22bis modem receive context.
Parameters
s The modem context.
Returns
0 for OK
v22bis_remote_loopback()
int v22bis_remote_loopback (v22bis_state_t * s, bool enable)
Request a loopback 2 for a V.22bis modem context.
Request a loopback 2 for a V.22bis modem context.
Parameters
s The modem context.
enable True to enable loopback, or false to disable it.
Returns
0 for OK, -1 for request reject.
v22bis_request_retrain()
int v22bis_request_retrain (v22bis_state_t * s, int bit_rate)
Request a retrain for a V.22bis modem context.
Request a retrain for a V.22bis modem context. A rate change may also be requested.
Parameters
s The modem context.
bit_rate The bit rate of the modem. Valid values are 1200 and 2400.
Returns
0 for OK, -1 for request rejected.
v22bis_restart()
int v22bis_restart (v22bis_state_t * s, int bit_rate)
Reinitialise an existing V.22bis modem context.
Reinitialise an existing V.22bis modem context, so it may be reused.
Parameters
s The modem context.
bit_rate The bit rate of the modem. Valid values are 1200 and 2400.
Returns
0 for OK, -1 for bad parameter.
v22bis_rx()
int v22bis_rx (v22bis_state_t * s, const int16_t amp[], int len)
Process a block of received V.22bis modem audio samples.
Process a block of received V.22bis modem audio samples.
Parameters
s The modem context.
amp The audio sample buffer.
len The number of samples in the buffer.
Returns
The number of samples unprocessed.
v22bis_rx_carrier_frequency()
float v22bis_rx_carrier_frequency (v22bis_state_t * s)
Get the current received carrier frequency.
Parameters
s The modem context.
Returns
The frequency, in Hertz.
References v22bis_state_s::carrier_phase_rate, and dds_frequencyf().
v22bis_rx_equalizer_state()
int v22bis_rx_equalizer_state (v22bis_state_t * s, complexf_t ** coeffs)
Get a snapshot of the current equalizer coefficients.
Get a snapshot of the current equalizer coefficients.
Parameters
coeffs The vector of complex coefficients.
Returns
The number of coefficients in the vector.
References v22bis_state_s::eq_coeff.
v22bis_rx_fillin()
int v22bis_rx_fillin (v22bis_state_t * s, int len)
Fake processing of a missing block of received V.22bis modem audio samples.
Fake processing of a missing block of received V.22bis modem audio samples. (e.g due to packet loss).
Parameters
s The modem context.
len The number of samples to fake.
Returns
The number of samples unprocessed.
References v22bis_state_s::logging, and span_log().
v22bis_rx_set_qam_report_handler()
void v22bis_rx_set_qam_report_handler (v22bis_state_t * s, qam_report_handler_t handler, void * user_data)
Set a handler routine to process QAM status reports
Parameters
s The modem context.
handler The handler routine.
user_data An opaque pointer passed to the handler routine.
v22bis_rx_set_signal_cutoff()
void v22bis_rx_set_signal_cutoff (v22bis_state_t * s, float cutoff)
Set the power level at which the carrier detection will cut in
Parameters
s The modem context.
cutoff The signal cutoff power, in dBm0.
References v22bis_state_s::carrier_off_power, v22bis_state_s::carrier_on_power, and power_meter_level_dbm0().
v22bis_rx_signal_power()
float v22bis_rx_signal_power (v22bis_state_t * s)
Get a current received signal power.
Parameters
s The modem context.
Returns
The signal power, in dBm0.
References power_meter_current_dbm0(), and v22bis_state_s::rx_power.
v22bis_rx_symbol_timing_correction()
float v22bis_rx_symbol_timing_correction (v22bis_state_t * s)
Get the current symbol timing correction since startup.
Parameters
s The modem context.
Returns
The correction.
References PULSESHAPER_COEFF_SETS, and v22bis_state_s::total_baud_timing_correction.
v22bis_set_get_bit()
void v22bis_set_get_bit (v22bis_state_t * s, span_get_bit_func_t get_bit, void * user_data)
Change the get_bit function associated with a V.22bis modem context.
Change the get_bit function associated with a V.22bis modem context.
Parameters
s The modem context.
get_bit The callback routine used to get the data to be transmitted.
user_data An opaque pointer.
v22bis_set_modem_status_handler()
void v22bis_set_modem_status_handler (v22bis_state_t * s, span_modem_status_func_t handler, void * user_data)
Change the modem status report function associated with a V.22bis modem receive context.
Change the modem status report function associated with a V.22bis modem receive context.
Parameters
s The modem context.
handler The callback routine used to report modem status changes.
user_data An opaque pointer.
References v22bis_state_s::status_handler, and v22bis_state_s::status_user_data.
v22bis_set_put_bit()
void v22bis_set_put_bit (v22bis_state_t * s, span_put_bit_func_t put_bit, void * user_data)
Change the put_bit function associated with a V.22bis modem context.
Change the get_bit function associated with a V.22bis modem context.
Parameters
s The modem context.
put_bit The callback routine used to process the data received.
user_data An opaque pointer.
v22bis_tx()
int v22bis_tx (v22bis_state_t * s, int16_t amp[], int len)
Generate a block of V.22bis modem audio samples.
Generate a block of V.22bis modem audio samples.
Parameters
s The modem context.
amp The audio sample buffer.
len The number of samples to be generated.
Returns
The number of samples actually generated.
v22bis_tx_power()
void v22bis_tx_power (v22bis_state_t * s, float power)
Adjust a V.22bis modem transmit context's output power.
Adjust a V.22bis modem transmit context's power output.
Parameters
s The modem context.
power The power level, in dBm0