spandsp: v27ter_rx.c File Reference
v27ter_rx.c File Reference
#include <stdlib.h>
#include <inttypes.h>
#include <string.h>
#include <stdio.h>
#include "spandsp/stdbool.h"
#include "floating_fudge.h"
#include "spandsp/telephony.h"
#include "spandsp/alloc.h"
#include "spandsp/logging.h"
#include "spandsp/fast_convert.h"
#include "spandsp/math_fixed.h"
#include "spandsp/saturated.h"
#include "spandsp/complex.h"
#include "spandsp/vector_float.h"
#include "spandsp/complex_vector_float.h"
#include "spandsp/vector_int.h"
#include "spandsp/complex_vector_int.h"
#include "spandsp/async.h"
#include "spandsp/power_meter.h"
#include "spandsp/arctan2.h"
#include "spandsp/dds.h"
#include "spandsp/complex_filters.h"
#include "spandsp/v29rx.h"
#include "spandsp/v27ter_rx.h"
#include "spandsp/private/logging.h"
#include "spandsp/private/power_meter.h"
#include "spandsp/private/v27ter_rx.h"
#include "v27ter_rx_4800_rrc.h"
#include "v27ter_rx_2400_rrc.h"
Macros
#define IAXMODEM_STUFF
#define FP_SCALE(x) (x)
#define FP_CONSTELLATION_SCALE(x) FP_SCALE(x)
#define CARRIER_NOMINAL_FREQ 1800.0f
#define BAUD_RATE_2400 1200
#define BAUD_RATE_4800 1600
#define EQUALIZER_DELTA 0.25f
#define V27TER_TRAINING_SEG_3_LEN 50
#define V27TER_TRAINING_SEG_5_LEN 1074
#define V27TER_TRAINING_SEG_6_LEN 8
Enumerations
enum {
TRAINING_STAGE_NORMAL_OPERATION = 0, TRAINING_STAGE_SYMBOL_ACQUISITION, TRAINING_STAGE_LOG_PHASE, TRAINING_STAGE_WAIT_FOR_HOP,
TRAINING_STAGE_TRAIN_ON_ABAB, TRAINING_STAGE_TEST_ONES, TRAINING_STAGE_PARKED
}
Functions
float v27ter_rx_carrier_frequency (v27ter_rx_state_t *s)
float v27ter_rx_symbol_timing_correction (v27ter_rx_state_t *s)
float v27ter_rx_signal_power (v27ter_rx_state_t *s)
void v27ter_rx_set_signal_cutoff (v27ter_rx_state_t *s, float cutoff)
int v27ter_rx_equalizer_state (v27ter_rx_state_t *s, complexf_t **coeffs)
Get a snapshot of the current equalizer coefficients.
int v27ter_rx (v27ter_rx_state_t *s, const int16_t amp[], int len)
Process a block of received V.27ter modem audio samples.
int v27ter_rx_fillin (v27ter_rx_state_t *s, int len)
Fake processing of a missing block of received V.27ter modem audio samples.
void v27ter_rx_set_put_bit (v27ter_rx_state_t *s, span_put_bit_func_t put_bit, void *user_data)
Change the put_bit function associated with a V.27ter modem receive context.
void v27ter_rx_set_modem_status_handler (v27ter_rx_state_t *s, span_modem_status_func_t handler, void *user_data)
Change the modem status report function associated with a V.27ter modem receive context.
logging_state_t * v27ter_rx_get_logging_state (v27ter_rx_state_t *s)
Get the logging context associated with a V.27ter modem receive context.
int v27ter_rx_restart (v27ter_rx_state_t *s, int bit_rate, bool old_train)
Reinitialise an existing V.27ter modem receive context.
v27ter_rx_state_t * v27ter_rx_init (v27ter_rx_state_t *s, int bit_rate, span_put_bit_func_t put_bit, void *user_data)
Initialise a V.27ter modem receive context.
int v27ter_rx_release (v27ter_rx_state_t *s)
Release a V.27ter modem receive context.
int v27ter_rx_free (v27ter_rx_state_t *s)
Free a V.27ter modem receive context.
void v27ter_rx_set_qam_report_handler (v27ter_rx_state_t *s, qam_report_handler_t handler, void *user_data)
Macro Definition Documentation
BAUD_RATE_2400
#define BAUD_RATE_2400 1200
The nominal baud or symbol rate in 2400bps mode
BAUD_RATE_4800
#define BAUD_RATE_4800 1600
The nominal baud or symbol rate in 4800bps mode
CARRIER_NOMINAL_FREQ
#define CARRIER_NOMINAL_FREQ 1800.0f
The nominal frequency of the carrier, in Hertz
EQUALIZER_DELTA
#define EQUALIZER_DELTA 0.25f
The adaption rate coefficient for the equalizer
V27TER_TRAINING_SEG_3_LEN
#define V27TER_TRAINING_SEG_3_LEN 50
The length of training segment 3, in symbols
V27TER_TRAINING_SEG_5_LEN
#define V27TER_TRAINING_SEG_5_LEN 1074
The length of training segment 5, in symbols
V27TER_TRAINING_SEG_6_LEN
#define V27TER_TRAINING_SEG_6_LEN 8
The length of training segment 6, in symbols
Function Documentation
v27ter_rx()
int v27ter_rx (v27ter_rx_state_t * s, const int16_t amp[], int len)
Process a block of received V.27ter modem audio samples.
Process a block of received V.27ter modem audio samples.
Parameters
s The modem context.
amp The audio sample buffer.
len The number of samples in the buffer.
Returns
The number of samples unprocessed.
v27ter_rx_carrier_frequency()
float v27ter_rx_carrier_frequency (v27ter_rx_state_t * s)
Get the current received carrier frequency.
Parameters
s The modem context.
Returns
The frequency, in Hertz.
References v27ter_rx_state_s::carrier_phase_rate, and dds_frequencyf().
v27ter_rx_equalizer_state()
int v27ter_rx_equalizer_state (v27ter_rx_state_t * s, complexf_t ** coeffs)
Get a snapshot of the current equalizer coefficients.
Get a snapshot of the current equalizer coefficients.
Parameters
coeffs The vector of complex coefficients.
Returns
The number of coefficients in the vector.
v27ter_rx_fillin()
int v27ter_rx_fillin (v27ter_rx_state_t * s, int len)
Fake processing of a missing block of received V.27ter modem audio samples.
Fake processing of a missing block of received V.27ter modem audio samples. (e.g due to packet loss).
Parameters
s The modem context.
len The number of samples to fake.
Returns
The number of samples unprocessed.
References v27ter_rx_state_s::logging, and span_log().
v27ter_rx_free()
int v27ter_rx_free (v27ter_rx_state_t * s)
Free a V.27ter modem receive context.
Free a V.27ter modem receive context.
Parameters
s The modem context.
Returns
0 for OK
v27ter_rx_get_logging_state()
logging_state_t* v27ter_rx_get_logging_state (v27ter_rx_state_t * s)
Get the logging context associated with a V.27ter modem receive context.
Get the logging context associated with a V.27ter modem receive context.
Parameters
s The modem context.
Returns
A pointer to the logging context
References v27ter_rx_state_s::logging.
v27ter_rx_init()
v27ter_rx_state_t* v27ter_rx_init (v27ter_rx_state_t * s, int bit_rate, span_put_bit_func_t put_bit, void * user_data)
Initialise a V.27ter modem receive context.
Initialise a V.27ter modem receive context.
Parameters
s The modem context.
bit_rate The bit rate of the modem. Valid values are 2400 and 4800.
put_bit The callback routine used to put the received data.
user_data An opaque pointer passed to the put_bit routine.
Returns
A pointer to the modem context, or NULL if there was a problem.
v27ter_rx_release()
int v27ter_rx_release (v27ter_rx_state_t * s)
Release a V.27ter modem receive context.
Release a V.27ter modem receive context.
Parameters
s The modem context.
Returns
0 for OK
v27ter_rx_restart()
int v27ter_rx_restart (v27ter_rx_state_t * s, int bit_rate, bool old_train)
Reinitialise an existing V.27ter modem receive context.
Reinitialise an existing V.27ter modem receive context.
Parameters
s The modem context.
bit_rate The bit rate of the modem. Valid values are 2400 and 4800.
old_train True if a previous trained values are to be reused.
Returns
0 for OK, -1 for bad parameter
v27ter_rx_set_modem_status_handler()
void v27ter_rx_set_modem_status_handler (v27ter_rx_state_t * s, span_modem_status_func_t handler, void * user_data)
Change the modem status report function associated with a V.27ter modem receive context.
Change the modem status report function associated with a V.27ter modem receive context.
Parameters
s The modem context.
handler The callback routine used to report modem status changes.
user_data An opaque pointer.
References v27ter_rx_state_s::status_handler, and v27ter_rx_state_s::status_user_data.
v27ter_rx_set_put_bit()
void v27ter_rx_set_put_bit (v27ter_rx_state_t * s, span_put_bit_func_t put_bit, void * user_data)
Change the put_bit function associated with a V.27ter modem receive context.
Change the put_bit function associated with a V.27ter modem receive context.
Parameters
s The modem context.
put_bit The callback routine used to handle received bits.
user_data An opaque pointer.
v27ter_rx_set_qam_report_handler()
void v27ter_rx_set_qam_report_handler (v27ter_rx_state_t * s, qam_report_handler_t handler, void * user_data)
Set a handler routine to process QAM status reports
Parameters
s The modem context.
handler The handler routine.
user_data An opaque pointer passed to the handler routine.
v27ter_rx_set_signal_cutoff()
void v27ter_rx_set_signal_cutoff (v27ter_rx_state_t * s, float cutoff)
Set the power level at which the carrier detection will cut in
Parameters
s The modem context.
cutoff The signal cutoff power, in dBm0.
References v27ter_rx_state_s::carrier_off_power, v27ter_rx_state_s::carrier_on_power, and power_meter_level_dbm0().
v27ter_rx_signal_power()
float v27ter_rx_signal_power (v27ter_rx_state_t * s)
Get a current received signal power.
Parameters
s The modem context.
Returns
The signal power, in dBm0.
References v27ter_rx_state_s::power, and power_meter_current_dbm0().
v27ter_rx_symbol_timing_correction()
float v27ter_rx_symbol_timing_correction (v27ter_rx_state_t * s)
Get the current symbol timing correction since startup.
Parameters
s The modem context.
Returns
The correction.
References v27ter_rx_state_s::bit_rate, and v27ter_rx_state_s::total_baud_timing_correction.